title: Heiler Gómez
#logo: /assets/img/headshot_circle.png
description: Data Scientist | Industrial Engineer | Machine Learning | Python | SQL
show_downloads: true
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-minimal
